# @package agent
_target_: agent.cql_cdsz.CQLCDSZeroAgent
name: cql_cdsz
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
#lr: 1e-4
actor_lr: 1e-4
critic_lr: 3e-4
critic_target_tau: 0.01

n_samples: 3
use_critic_lagrange: False
alpha: 50                    # used if use_critic_lagrange is False
target_cql_penalty: 5.0      # used if use_critic_lagrange is True

use_tb: True
hidden_dim: 256
#stddev_schedule: 0.2
#stddev_clip: 0.3
nstep: 1
batch_size: 1024
has_next_action: False

num_expl_steps: ???   # to be specified later